name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version if needed

      - name: Install Dependencies
        run: |
          cd src
          npm install

      - name: Build Frontend
        run: |
          cd src
          npm run build

      - name: Copy Build to Public Directory
        run: |
          mkdir -p public
          cp -r src/build/* public/ || echo "No files to copy, build may have failed."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
