name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for Backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Backend Dependencies
        working-directory: server
        run: npm install

      - name: Run Backend Tests
        working-directory: server
        run: npm test

  # Job for Frontend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Frontend Dependencies
        working-directory: src
        run: npm install

      - name: Run Frontend Tests
        working-directory: src
        run: npm test

      - name: Build Frontend
        working-directory: src
        run: npm run build

  # Job for Deployment
  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
