name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job cho Backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Backend Dependencies
        working-directory: server
        run: nodemon server/index.js

      - name: Run Backend Tests
        working-directory: server
        run: npm test

  # Job cho Frontend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Frontend Dependencies
        working-directory: src
        run: npm install

      - name: Run Frontend Tests
        working-directory: src
        run: npm test

      - name: Build Frontend
        working-directory: src
        run: react-scripts start

  # Job Deploy (nếu cần)
  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Thêm lệnh deploy của bạn ở đây
