name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job cho Backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Backend Dependencies
        working-directory: server
        run: npm install

      - name: Run Backend Tests
        working-directory: server
        run: npm test

  # Job cho Frontend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Frontend Dependencies
        working-directory: src
        run: npm install

      - name: Run Frontend Tests
        working-directory: src
        run: npm test

      - name: Build Frontend
        working-directory: src
        run: npm run build

 # Job Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
  
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku auth:token
  
      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/YOUR_APP_NAME.git
          git push heroku main
